name: Sample workflow

env:
   GLOBAL_MSG: "This is a Workflow global test message!!!"

on: [push]

jobs:
  printout:
     name: Printout Message
     runs-on: ubuntu-latest
     env:
       JOBS_MSG: "This is a jobs level message!!!"
     steps:
       - name: Printout Global Message
         run: 
           echo "GLOBAL_MESSAGE :$GLOBAL_MSG"

       - name: Printout Jobs Level Message
        run: 
           echo "JOBS MESSAGE : $JOBS_MSG"
