name: Printout workflow

env:
   GLOBAL_MSG: "This is a GLOBAL Level message!!!"

on: [push]

jobs:
  printout:
     name: Printout Message
     runs-on: ubuntu-latest
     env:
       JOBS_MSG: "This is a JOBS level message!!!"
     steps:
       - name: Printout Global Message
         run: echo "GLOBAL_MESSAGE :$GLOBAL_MSG"
      
       - name: Printout Jobs Level Message
         run: 
           echo "JOBS MESSAGE :$JOBS_MSG"
            
       - name: Printout Steps Level Message
         env:
            STEPS_MSG: "This is a STEPS level message!!!" 
         run: echo "STEP_MSG :$STEPS_MSG"
